# Generated by Django 3.0.5 on 2021-01-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_remove_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day', models.CharField(max_length=20)),
                ('isActive', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.doctor')),
            ],
        ),
    ]
