# Generated by Django 3.0.5 on 2021-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
