# Generated by Django 3.0.5 on 2021-01-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20210112_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
    ]
